=== TarikDjebienMasterDegree/PXML/TPs/TP2/bin/exercice2/Exercice2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bibliographie (livre*,article*) >

<!-- LIVRE -->
<!ELEMENT livre (titre, auteur+, tome+, informationLivre) >
<!ELEMENT tome EMPTY >
<!ATTLIST tome nb-pages CDATA #REQUIRED 
               soustitre CDATA #IMPLIED
               >
<!ELEMENT informationLivre (editeur, lieuEdition, lieuImpression)> 
<!ATTLIST informationLivre isbn ID #REQUIRED >
<!ELEMENT editeur (#PCDATA) >
<!ELEMENT lieuEdition (#PCDATA) >
<!ELEMENT lieuImpression (#PCDATA) >

<!-- ARTICLE -->
<!ELEMENT article (titre, auteur+, reference, avisPersonnel?) >
<!ELEMENT reference (journal)+ >
<!ELEMENT journal (nom-journal, anneePublication) >
<!ELEMENT nom-journal EMPTY >
<!ATTLIST nom-journal nom-journal CDATA "L'Epique"
                     numeroPage CDATA #REQUIRED
                     numeroJournal CDATA #REQUIRED >
<!ELEMENT anneePublication EMPTY >
<!ATTLIST anneePublication annee (2009|2010|2011|avant-2009|inconnue)  "inconnue" >
<!ELEMENT nomJournal (#PCDATA) >           
<!ELEMENT avisPersonnel (#PCDATA) >

<!-- COMMUN -->
<!ELEMENT titre (#PCDATA) >
<!ATTLIST titre soustitre CDATA #IMPLIED>
<!ELEMENT auteur (#PCDATA) >

=== TarikDjebienMasterDegree/PXML/TPs/TP2/ressources/exercice2/Exercice2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliographie SYSTEM "Exercice2.dtd" >
<bibliographie>
  <livre>
    <titre soustitre="">titre</titre>
    <auteur>auteur</auteur>
    <tome nb-pages="" soustitre=""/>
    <informationLivre isbn="idvalue0">
      <editeur>editeur</editeur>
      <lieuEdition>lieuEdition</lieuEdition>
      <lieuImpression>lieuImpression</lieuImpression>
    </informationLivre>
  </livre>
  <article>
    <titre soustitre="">titre</titre>
    <auteur>auteur</auteur>
    <reference>
      <journal>
        <nom-journal nom-journal="L'Epique" numeroJournal="" numeroPage=""/>
        <anneePublication annee="inconnue"/>
      </journal>
    </reference>
    <avisPersonnel>avisPersonnel</avisPersonnel>
  </article>
</bibliographie>
