=== TarikDjebienMasterDegree/PXML/TPs/TP2/bin/exercice5/Exercice5.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT lesItineraires (itineraire)*>
<!ATTLIST itineraire id ID #REQUIRED>
<!ELEMENT itineraire (enTete, initialisation, etapes)>

<!-- EN TETE -->
<!ELEMENT enTete (source, destination, date, mode, preference, vitesseMarcheAPied, tempsDeParcours)>
<!ELEMENT source EMPTY>
<!ATTLIST source city CDATA #REQUIRED 
                 place CDATA #REQUIRED>

<!ELEMENT destination EMPTY>
<!ATTLIST destination city CDATA #REQUIRED 
                      place CDATA #REQUIRED>

<!ELEMENT date EMPTY>
<!ATTLIST date dayInWeek CDATA #IMPLIED 
               dayInMonth CDATA #REQUIRED 
               month CDATA #REQUIRED 
               HH CDATA #REQUIRED
               mm CDATA #REQUIRED>

<!ELEMENT mode (#PCDATA)>

<!ELEMENT preference (#PCDATA)>

<!ELEMENT vitesseMarcheAPied (#PCDATA)>

<!ELEMENT tempsDeParcours EMPTY>
<!ATTLIST tempsDeParcours HH CDATA #REQUIRED
                          mm CDATA #REQUIRED>

<!-- INITIALISATION -->
<!ELEMENT initialisation (depart, objectif, transport)>
<!ELEMENT depart EMPTY>
<!ATTLIST depart cityRef CDATA #REQUIRED
                 placeRef CDATA #REQUIRED>
<!ELEMENT objectif (#PCDATA)>
<!ELEMENT transport (type, duree)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT duree EMPTY>
<!ATTLIST duree mm CDATA #REQUIRED>

<!-- ETAPES -->
<!ELEMENT etapes (etape)+>
<!ELEMENT etape (predirective, postdirective, correspondance?)>
<!ATTLIST etape id ID #REQUIRED>

<!ELEMENT predirective (heureDepart, objectif, transport)>
<!ELEMENT heureDepart EMPTY>
<!ATTLIST heureDepart HH CDATA #REQUIRED mm CDATA #REQUIRED>

<!ELEMENT postdirective (heureArrivee, objectif)>
<!ELEMENT heureArrivee EMPTY>
<!ATTLIST heureArrivee HH CDATA #REQUIRED mm CDATA #REQUIRED>

<!ELEMENT correspondance (duree)>

=== TarikDjebienMasterDegree/PXML/TPs/TP2/bin/exercice5/Exercice5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lesItineraires SYSTEM "Exercice5.dtd" >
<?xml-stylesheet href="Exercice5.css" type"text/css"?>
<!-- author : Djebien Tarik -->
<!-- PXML.TP2.Exercice5 -->

<lesItineraires>
	<itineraire id="itineraire1">
	    <!-- Une En Tete qui resume l'itineraire demandee -->
		<enTete>
			<source city='Seclin' place='Centre_hospitalier' />
			<destination city='Roubaix' place='Avenue_Motte' />
			<date dayInWeek='Vendredi' dayInMonth='6' month='janvier' HH='11'
				mm='45' />
			<mode>Métro-Tramway-Bus-Car</mode>
			<preference>Arriver le plus rapidement</preference>
			<vitesseMarcheAPied>Normale</vitesseMarcheAPied>
			<tempsDeParcours HH='1' mm='32' />
		</enTete>
        <!-- Une situation initiale -->
		<initialisation>
			<depart cityRef='Seclin' placeRef='Centre_hospitalier' />
			<objectif>rejoindre à pied l’arrêt Seclin - apolda</objectif>
			<transport>
				<type>marche à pieds</type>
				<duree mm='10' />
			</transport>
		</initialisation>
		<!-- L'itineraire est alors decompose en taches ordonnancee a accomplir -->
		<etapes>
			<etape id='step1'>
				<predirective>
					<heureDepart HH='11' mm='51' />
					<objectif>Prendre le Bus ligne 229 en direction de Lille - CHR B
						Calmette
					</objectif>
					<transport>
						<type>Bus TRANSPOLE</type>
						<duree mm='31' />
					</transport>
				</predirective>
				<postdirective>
					<heureArrivee HH='12' mm='22' />
					<objectif>Descendre à l’arrêt Lille - CHR B Calmette</objectif>
				</postdirective>
				<correspondance>
					<duree mm='4' />
				</correspondance>
			</etape>
			<etape id='step2'>
				<predirective>
					<heureDepart HH='12' mm='26' />
					<objectif>Prendre le Métro ligne 1 en direction de Villeneuve
						d’Ascq - 4 Cantons
					</objectif>
					<transport>
						<type>Métro TRANSPOLE</type>
						<duree mm='9' />
					</transport>
				</predirective>
				<postdirective>
					<heureArrivee HH='12' mm='35' />
					<objectif>Descendre à l’arrêt Lille - Gare Lille Flandres
					</objectif>
				</postdirective>
				<correspondance>
					<duree mm='3' />
				</correspondance>
			</etape>
			<etape id='step3'>
				<predirective>
					<heureDepart HH='12' mm='30' />
					<objectif>Prendre le Métro ligne 2 en direction de Tourcoing - CH
						Dron
					</objectif>
					<transport>
						<type>Métro TRANSPOLE</type>
						<duree mm='17' />
					</transport>
				</predirective>
				<postdirective>
					<heureArrivee HH='12' mm='55' />
					<objectif>Descendre à l’arrêt Roubaix - Epeule Montesquieu
					</objectif>
				</postdirective>
				<correspondance>
					<duree mm='9' />
				</correspondance>
			</etape>
			<etape id='step4'>
				<predirective>
					<heureDepart HH='13' mm='04' />
					<objectif>Prendre le Bus ligne 25 en direction de Roubaix -
						fraternité
					</objectif>
					<transport>
						<type>Bus TRANSPOLE</type>
						<duree mm='9' />
					</transport>
				</predirective>
				<postdirective>
					<heureArrivee HH='13' mm='13' />
					<objectif>Descendre à l’arrêt Roubaix - Avenue Motte</objectif>
				</postdirective>
			</etape>
		</etapes>
	</itineraire>
</lesItineraires>
