=== TarikDjebienMasterDegree/PXML/TPs/TP2/bin/exercice1/Exercice1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bibliographie (livre*,article*) >

<!-- LIVRE -->
<!ELEMENT livre (titre, auteur+, tome+, informationLivre) >
<!ELEMENT tome EMPTY >
<!ATTLIST tome nbPage CDATA #REQUIRED >
<!ELEMENT informationLivre (editeur, lieuEdition, lieuImpression)> 
<!ATTLIST informationLivre isbn ID #REQUIRED >
<!ELEMENT editeur (#PCDATA) >
<!ELEMENT lieuEdition (#PCDATA) >
<!ELEMENT lieuImpression (#PCDATA) >

<!-- ARTICLE -->
<!ELEMENT article (titre, auteur+, reference, avisPersonnel?) >
<!ELEMENT reference (nomJournal) >
<!ATTLIST reference numeroPage CDATA #REQUIRED
                    anneePublication CDATA #REQUIRED
                    numeroJournal CDATA #REQUIRED >
<!ELEMENT nomJournal (#PCDATA) >           
<!ELEMENT avisPersonnel (#PCDATA) >

<!-- COMMUN -->
<!ELEMENT titre (#PCDATA) >
<!ELEMENT auteur (#PCDATA) >

=== TarikDjebienMasterDegree/PXML/TPs/TP2/ressources/exercice1/Exercice1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliographie SYSTEM "Exercice1.dtd" >
<bibliographie>
	<livre>
		<titre>Le tour du monde en 80 jours</titre>
		<auteur>Verne Jules</auteur>
		<tome nbPage="124" />
		<informationLivre isbn="A-2001070419">
			<editeur>SuperEditor</editeur>
			<lieuEdition>Lille</lieuEdition>
			<lieuImpression>Paris</lieuImpression>
		</informationLivre>
	</livre>
	<livre>
		<titre>Martine écrit en UTF8</titre>
		<auteur>Gilbert Delahaye</auteur>
		<tome nbPage="40" />
		<informationLivre isbn="B-4578512454">
			<editeur>asciiEdition</editeur>
			<lieuEdition>Konisberg</lieuEdition>
			<lieuImpression>M5</lieuImpression>
		</informationLivre>
	</livre>
	<article>
		<titre>Spring Aspect Object Programming</titre>
		<auteur>Tarik</auteur>
		<reference anneePublication="2012" numeroJournal="1"
			numeroPage="20">
			<nomJournal>Practice with samples</nomJournal>
		</reference>
		<avisPersonnel>Article présentant la programmation orienté aspect dans
			le FrameWork JEE Spring</avisPersonnel>
	</article>
</bibliographie>
